### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by pchiusano** [haskell-cryptography/cacophony#1]
Awesome library! I'd like to try using it for my project, but I noticed there has been some API changes since the last release. Any chance of you cutting a release sometime soon?

Also, unrelated, but is there a good place to ask questions about usage of the library?

**Comment by centromere** [comment]
Hi @pchiusano. I am unable to cut a release until @vincenthz releases a new version of [cryptonite](https://github.com/haskell-crypto/cryptonite).

I would prefer to keep the issue tracker focused on bug reports. Feel free to contact me via email with questions.

**Comment by pchiusano** [comment]
Ah, okay. Makes sense.

**Comment by centromere** [comment]
@pchiusano: A new release of cryptonite was cut a few hours ago. As such I've cut a new release of cacophony.

**Comment by pchiusano** [comment]
Sweet! Thanks. Looking forward to trying it out.

**Comment by tmciver** [comment]
@centromere I'm working with @pchiusano on his project that may use your library and I have some questions about it.  What's the best way to contact you about these?  I couldn't find your email address.  Maybe a gitter chatroom would be best . . .

**Comment by centromere** [comment]
@tmciver: @pchiusano has it.
