### ISSUE TITLE
test vectors

### ISSUE THREAD

**Issue by mimoo** [haskell-cryptography/cacophony#6]
Hello,

I noticed that in the test vectors for `Noise_XX_25519_ChaChaPoly_SHA512`, after the handshake has completed the server will send the first payload to the client, which is the inverse of what other test vectors do (the client send the first payload).

Is this normal?

**Comment by centromere** [comment]
Yes. The test vector format [specifies it](https://github.com/noiseprotocol/noise_wiki/wiki/Test-vectors) as such:

> The messages array describes a conversation alternating between the initiator and responder, starting with the initiator. No distinction is made between when the handshake begins and when it is complete. For example, if a handshake pattern has three messages in it, the responder will send the first non-handshake Noise message. For one-way patterns the messages simply flow from the initiator to the responder.

**Comment by mimoo** [comment]
Ah, didn't notice there was a wiki here :) I'd suggest adding link to the README file now that you're the reference for Noise's test vectors.

Thanks!

**Comment by centromere** [comment]
I appreciate the suggestion.
